# Generated by Django 4.1.7 on 2023-03-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Електронна пошта')),
                ('anons', models.CharField(max_length=15, verbose_name='Телефон')),
                ('full_text', models.TextField(max_length=20, verbose_name="ім'я")),
                ('age', models.IntegerField(verbose_name='вік')),
                ('Happy_or_not', models.FloatField(verbose_name='Рівень щастя від 1 до 10')),
                ('Have_car_or_not', models.BooleanField(verbose_name='Машина є?')),
            ],
            options={
                'verbose_name': 'Новина',
                'verbose_name_plural': 'Новини',
            },
        ),
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='About2',
        ),
    ]
